### ISSUE TITLE
Maybe mime 0.2.0 is updated in a wrong way?

### ISSUE THREAD

**Issue by fengsp** [cybergeek94/mime_guess#17]
mime_guess is updated to use mime 0.2.0 and it is a incompatible version change, in this case, I think mime_guess need to update itself to a incompatible version.  Now because other crates are using mime 0.1.3 and there is a version conflict, I have to use the older version of mime_guess.

**Comment by cybergeek94** [comment]
Yeah I thought there might be a problem there. I'll yank 1.5.1 and publish as 1.6.

**Comment by nox** [comment]
No? You can very well tell your local repository to use mime 0.1 with mime_guess 1.5.1.

**Comment by nox** [comment]
```
cargo update -p mime --precise 0.1.3
```

**Comment by nox** [comment]
Oh well, it's been published already.

**Comment by nox** [comment]
@cybergeek94 Actually 1.6.0 will not change anything about @fengsp's problem because 1.6.0 is compatible with 1.5.1 from semver's POV. If you wanted to make a backwards-incompatible bump you should have published 2.0.0.

**Comment by fengsp** [comment]
@nox @cybergeek94 Yes, 1.6.0 won't solve my problem.  This is thin ice here, I don't know how to solve this.  If we have several crates that already reach 1.0.0 and they all depend on a crate with 0.x.x,  anyone of them who doesn't use the latest version of that crate will break the whole build.

**Comment by cybergeek94** [comment]
It's absurd to bump the major version for every minor breaking change. Even Rust doesn't strictly obey semver.

**Comment by fengsp** [comment]
The only thing I can come up with is that do not bump to 1.x.x until all dependencies does so.

**Comment by nox** [comment]
@cybergeek94 Crates.io expect semver compliance, and bumping minor and patch when you are after 1.y.z is exactly the same thing.

@fengsp Just run the cargo command I pasted.

**Comment by fengsp** [comment]
@nox As the crate owner, I do not want all my crate users run it.

**Comment by cybergeek94** [comment]
@fengsp Bind to `mime_guess=1.5`

**Comment by nox** [comment]
@cybergeek94 http://doc.crates.io/manifest.html#the-package-section

> After 1.0.0, only make breaking changes when you increment the major version. In Rust, breaking changes include adding fields to structs or variants to enums. Don’t break the build.

@fengsp If you explicitly depend on mime 0.1 in your own crate, Cargo should be able to just use that. Alternatively you can do mime_guess = "=1.5", but not "1.5" because "1.5" can select 1.6.

**Comment by fengsp** [comment]
@cybergeek94 Yeah, now I am doing `mime_guess = "=1.5.0"`.

**Comment by fengsp** [comment]
@cybergeek94 I hope to have a better solution.

**Comment by fengsp** [comment]
@nox If you explicitly depend on mime 0.1 in your own crate, the build will still fail :(

**Comment by nox** [comment]
@fengsp Ok, now that's a problem.

Please do "=1.5.0" for now, and I'm pinging @steveklabnik and @wycats because that's certainly not the first time this happens.

**Comment by nox** [comment]
https://github.com/rust-lang/cargo/issues/2064

**Comment by steveklabnik** [comment]
Sorry all, it's been a busy week for me.

@cybergeek94 

> Even Rust doesn't strictly obey semver.

Yes, we do :p or rather, if you can point out how we're not, I'd like to hear about it.

> Please do "=1.5.0" for now, and I'm pinging @steveklabnik and @wycats because that's certainly not the first time this happens.

Yes. `^` is the default, because it's what you want virtually all of the time. The thing about `0.y.z` being the same as `1.y.z` was made to follow most people's expectations. I personally don't like it, but it's the way several other ecosystems handle it, and many people _do_ like it...

**Comment by Ogeon** [comment]
I just want to drop in and say that I just realized that this silently broke Rustful. I should update both Hyper and Multipart, anyway, but it's still not fun when things breaks without warning. These things are hard when it comes to 0.x.y versions, since there are no clear rules, but it looks like most authors treats the x number as a major version. It's probably best to go with the flow and be at least that strict, if not more, as long as Cargo works as it does.

Changing a the version of a crate that is used in the public interface _is_ a breaking change, so it would be great if Cargo could become a bit more intelligent when it comes to how it chooses to update them. We'll just have to be careful until then. Downstream crates should really follow the same update pattern as upstream crates uses, and try to reexport types wherever that's appropriate.

Accidents happens, but we can at least be careful.

**Comment by cybergeek94** [comment]
This was wholeheartedly my mistake. In semver, `1.x -> 1.(x+1)` is considered a backwards-compatible change but `0.x -> 0.(x+1)` isn't. When I refactored `mime_guess` to use PHF instead of an ordered list + binary search, I considered it a breaking change and so bumped the first number `0.x -> 1.x`, but I now know that's not a good idea unless all your dependencies have also made that transition and you're ready for release.

The best, but probably most destructive, thing to do would be to yank all `>= 1.0` releases of `mime_guess` and continue the `0.x` scheme until all of its dependencies stabilize.

**Comment by Ogeon** [comment]
Yanking won't break anything, so it's not super destructive, but jumping back to 0.x releases may be a bit confusing at first. Probably worth it, though, as long as the dependencies are unstable.
